[package]
name = "create-rust-app_cli"
description = "Set up a modern rust+react web app by running one command."
version = "8.1.1"
authors = ["Haris <4259838+Wulf@users.noreply.github.com>"]
edition = "2018"
readme = "../README.md"
repository = "https://github.com/Wulf/create-rust-app"
license = "MIT OR Apache-2.0"
keywords = ["react", "typescript", "generation", "backend", "frontend"]
categories = ["command-line-utilities", "development-tools", "web-programming", "config", "database"]
default-run = "create-rust-app"

[dependencies]
Inflector = "0.11.4"
anyhow = "1.0.68"
console = "0.15.5"
dialoguer = "0.10.3"
indoc = "1.0.8"
rust-embed = "6.3.0"
structopt = "0.3.26"
toml = "0.5.8"
tsync = "1"

# check cli version
update-informer = "0.6.0"

# for qsync exclusively
regex = "1.5.4"
syn = { version = "1.0.75", features = ["full", "extra-traits", "parsing"] }
walkdir = "2.3.2"

[[bin]]
name = "create-rust-app"
path = "src/main.rs"
